// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmZOwgu8f5QY5KKZyvy1flVHxdUuWfHiw',
    appId: '1:276943391656:android:f5e8fbb14fc87a06e76b9d',
    messagingSenderId: '276943391656',
    projectId: 'condo-tech-b7673',
    storageBucket: 'condo-tech-b7673.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqw9HX3B0wUQSNpboprJTnMIy3AWU1NHE',
    appId: '1:276943391656:web:ce0fcb31ac66cfaee76b9d',
    messagingSenderId: '276943391656',
    projectId: 'condo-tech-b7673',
    authDomain: 'condo-tech-b7673.firebaseapp.com',
    storageBucket: 'condo-tech-b7673.appspot.com',
    measurementId: 'G-YQ9CKCN5X4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr1PKQ1tTx2hZVWaHoE96JxhipI6KfKkY',
    appId: '1:276943391656:ios:79a763d63f0e44f2e76b9d',
    messagingSenderId: '276943391656',
    projectId: 'condo-tech-b7673',
    storageBucket: 'condo-tech-b7673.appspot.com',
    iosBundleId: 'com.example.condotech',
  );

}